# Generated by Django 2.2 on 2020-10-20 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descriptions',
            old_name='desciption',
            new_name='description',
        ),
    ]
