# Generated by Django 2.2 on 2020-10-20 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_auto_20201020_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='description',
        ),
        migrations.RemoveField(
            model_name='descriptions',
            name='id',
        ),
        migrations.AddField(
            model_name='courses',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='descriptions',
            name='courses',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='courses_app.Courses'),
            preserve_default=False,
        ),
    ]
