# Generated by Django 2.2 on 2020-10-21 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_auto_20201020_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='id',
        ),
        migrations.RemoveField(
            model_name='descriptions',
            name='courses',
        ),
        migrations.AddField(
            model_name='courses',
            name='description',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='courses_app.Descriptions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='descriptions',
            name='id',
            field=models.AutoField(auto_created=True, default='1', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
